import{a as l,S as v,i as u}from"./assets/vendor-CVWx-W0A.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();l.defaults.baseURL="https://pixabay.com/api/";const w="36536171-20dffb6feebbd7a17f40a2c96",d=async(s,e)=>{try{return(await l.get("",{params:{key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}catch(n){console.log(n)}},p=document.querySelector(".gallery"),m=document.querySelector(".loader"),g=document.querySelector(".loadMoreBtn"),q=({largeImageURL:s,webformatURL:e,tags:n,likes:a,views:t,comments:o,downloads:i})=>` <li class="item">
              <a href=${s}>
                <img src=${e} alt=${n}>
                <div class="img_text_list">
                  <p><span>Likes</span>${a}</p>
                  <p><span>Views</span>${t}</p>
                  <p><span>Comments</span>${o}</p>
                  <p><span>Downloads</span>${i}</p>
                </div>
              </a>
            </li>`,y=s=>{const e=s.map(q).join("");p.insertAdjacentHTML("beforeend",e),new v(".gallery > li > a").refresh()},M=()=>{p.innerHTML=""},f=()=>{m.classList.remove("visually-hidden")},c=()=>{m.classList.add("visually-hidden")},h=()=>{g.classList.remove("visually-hidden")},b=()=>{g.classList.add("visually-hidden")},S=document.querySelector(".form"),H=document.querySelector(".loadMoreBtn"),O=document.querySelector(".gallery");u.settings({timeout:5e3,resetOnHover:!0,transitionIn:"flipInX",maxWidth:"400px",position:"topRight",transitionOut:"flipOutX"});const r={query:"",pageNumber:1,totalHits:0,perPage:0},L=()=>{const e=O.getBoundingClientRect().bottom-window.innerHeight;return window.scrollBy({top:e-30,behavior:"smooth"})},P=async s=>{s.preventDefault(),M(),b(),f();const n=new FormData(s.target).get("search-text");try{const a=await d(n,1);y(a.hits),h(),L(),r.query=n,r.totalHits=a.totalHits,r.pageNumber+=1,r.perPage+=a.hits.length}catch(a){console.log(a)}c(),s.target.reset()};S.addEventListener("submit",P);const N=async()=>{if(f(),!(r.totalHits>r.perPage)){b(),c(),u.info({message:"We're sorry, but you've reached the end of search results."}),r.query="",r.pageNumber=1,r.totalHits=0,r.perPage=0;return}try{const e=await d(r.query,r.pageNumber);y(e.hits),h(),L(),r.pageNumber+=1,r.perPage+=e.hits.length}catch(e){console.log(e)}c()};H.addEventListener("click",N);
//# sourceMappingURL=index.js.map
