import{a as u,S as w,i as l}from"./assets/vendor-CVWx-W0A.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();u.defaults.baseURL="https://pixabay.com/api/";const v="36536171-20dffb6feebbd7a17f40a2c96",d=async(s,e)=>{try{return(await u.get("",{params:{key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}catch(n){console.log(n)}},p=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".loadMoreBtn"),q=({largeImageURL:s,webformatURL:e,tags:n,likes:a,views:r,comments:o,downloads:i})=>` <li class="item">
              <a href=${s}>
                <img src=${e} alt=${n}>
                <div class="img_text_list">
                  <p><span>Likes</span>${a}</p>
                  <p><span>Views</span>${r}</p>
                  <p><span>Comments</span>${o}</p>
                  <p><span>Downloads</span>${i}</p>
                </div>
              </a>
            </li>`,g=s=>{const e=s.map(q).join("");p.insertAdjacentHTML("beforeend",e),new w(".gallery > li > a").refresh()},M=()=>{p.innerHTML=""},f=()=>{m.classList.remove("visually-hidden")},c=()=>{m.classList.add("visually-hidden")},y=()=>{h.classList.remove("visually-hidden")},b=()=>{h.classList.add("visually-hidden")},S=document.querySelector(".form"),P=document.querySelector(".loadMoreBtn"),H=document.querySelector(".gallery");l.settings({timeout:5e3,resetOnHover:!0,transitionIn:"flipInX",maxWidth:"400px",position:"topRight",transitionOut:"flipOutX"});const t={query:"",pageNumber:1,totalHits:0,perPage:0},L=()=>{const e=H.getBoundingClientRect().height*2;return window.scrollBy({top:e,behavior:"smooth"})},N=async s=>{s.preventDefault(),M(),b(),f(),t.query="",t.pageNumber=1,t.totalHits=0,t.perPage=0;const n=new FormData(s.target).get("search-text");if(n.length!==0){try{const a=await d(n,1);if(a.hits.length===0)throw new Error("no Images");g(a.hits),y(),L(),t.query=n,t.totalHits=a.totalHits,t.pageNumber+=1,t.perPage+=a.hits.length}catch(a){l.error({message:`${a}`})}c(),s.target.reset()}};S.addEventListener("submit",N);const O=async()=>{if(f(),!(t.totalHits>t.perPage)){b(),c(),l.info({message:"We're sorry, but you've reached the end of search results."}),t.query="",t.pageNumber=1,t.totalHits=0,t.perPage=0;return}try{const e=await d(t.query,t.pageNumber);if(e.hits.length===0)throw new Error("no Images");g(e.hits),L(),y(),t.pageNumber+=1,t.perPage+=e.hits.length}catch(e){l.error({message:`${e}`})}c()};P.addEventListener("click",O);
//# sourceMappingURL=index.js.map
