import{a as d,S as v,i as c}from"./assets/vendor-CVWx-W0A.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(t){if(t.ep)return;t.ep=!0;const a=n(t);fetch(t.href,a)}})();d.defaults.baseURL="https://pixabay.com/api/";const M="36536171-20dffb6feebbd7a17f40a2c96",m=async(r,e)=>{try{return(await d.get("",{params:{key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}catch(n){console.log(n)}},p=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector(".loadMoreBtn"),S=new v(".gallery > li > a"),q=({largeImageURL:r,webformatURL:e,tags:n,likes:s,views:t,comments:a,downloads:i})=>` <li class="item">
              <a href=${r}>
                <img src=${e} alt=${n}>
                <div class="img_text_list">
                  <p><span>Likes</span>${s}</p>
                  <p><span>Views</span>${t}</p>
                  <p><span>Comments</span>${a}</p>
                  <p><span>Downloads</span>${i}</p>
                </div>
              </a>
            </li>`,f=r=>{const e=r.map(q).join("");p.insertAdjacentHTML("beforeend",e),S.refresh()},x=()=>{p.innerHTML=""},y=()=>{h.classList.remove("visually-hidden")},l=()=>{h.classList.add("visually-hidden")},b=()=>{g.classList.remove("visually-hidden")},u=()=>{g.classList.add("visually-hidden")},H=document.querySelector(".form"),N=document.querySelector(".loadMoreBtn");c.settings({timeout:5e3,resetOnHover:!0,transitionIn:"flipInX",maxWidth:"400px",position:"topRight",transitionOut:"flipOutX",iconUrl:"./img/octagon.svg",maxWidth:"400px"});const o={query:"",pageNumber:1,totalHits:0,perPage:0},L=()=>{const r=document.querySelector(".item");if(!r)return;const e=r.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})},w=()=>{o.query="",o.pageNumber=1,o.totalHits=0,o.perPage=0},O=async r=>{r.preventDefault(),x(),u(),w();const n=new FormData(r.target).get("search-text");if(n.length!==0){y();try{const s=await m(n,1);if(s.hits.length===0)throw new Error("no Images");f(s.hits),s.totalHits>s.hits.length||(u(),l(),c.info({message:"No content to load"})),b(),L(),o.query=n,o.totalHits=s.totalHits,o.pageNumber+=1,o.perPage+=s.hits.length}catch(s){c.error({message:`${s.message}`,messageColor:"#fff",color:"#EF4040"})}l(),r.target.reset()}};H.addEventListener("submit",O);const P=async()=>{if(y(),u(),!(o.totalHits>o.perPage)){u(),l(),c.info({iconUrl:"",message:"We're sorry, but you've reached the end of search results."}),w();return}try{const e=await m(o.query,o.pageNumber);if(e.hits.length===0)throw new Error("no Images");f(e.hits),b(),L(),o.pageNumber+=1,o.perPage+=e.hits.length}catch(e){c.error({message:`${e.message}`,messageColor:"#fff",color:"#EF4040",maxWidth:"400px"})}l()};N.addEventListener("click",P);
//# sourceMappingURL=index.js.map
